library(mgcv)

# Generate the same test data as Python (read from CSV generated by debug_parity.py)
# First generate data in R matching Python's rng(42) layout
# Use the validate_pymgcv.py poisson dataset approach
d <- read.csv('test_poisson_data.csv')
cat('n =', nrow(d), '\n')

m <- gam(y ~ s(x), data=d, method='REML', family=poisson())
S <- m$smooth[[1]][['S']][[1]]
eigs <- sort(eigen(S)$values, decreasing=TRUE)
cat('mgcv penalty eigenvalues:\n')
cat(round(eigs, 6), '\n')
cat('rank =', sum(eigs > 1e-10), '\n')
cat('max_eig =', eigs[1], '\n')
cat('mgcv sp =', m$sp, '\n')
cat('effective lambda (sp * max_eig) =', m$sp * eigs[1], '\n')
cat('mgcv edf =', sum(m$edf), '\n')
cat('mgcv fitted[1] =', m$fitted.values[1], '\n')
